'use strict';
const PDFDocument = require('pdfkit');
const { getFinancialHealthScore, getLoanRecommendations } = require('./storage');

const GREEN  = '#128C7E';
const DARK   = '#1a1a2e';
const GREY   = '#666666';
const LIGHT  = '#f5f5f5';
const WHITE  = '#ffffff';
const RED    = '#e74c3c';

function formatRM(amount) {
  return `RM ${amount.toFixed(2)}`;
}

function formatDate(dateStr) {
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-MY', { day: '2-digit', month: 'long', year: 'numeric' });
}

function drawHLine(doc, y, color = '#cccccc') {
  doc.moveTo(50, y).lineTo(545, y).strokeColor(color).lineWidth(0.5).stroke();
}

function drawTableRow(doc, y, cols, isHeader = false, isTotal = false) {
  const bg = isHeader ? GREEN : isTotal ? LIGHT : WHITE;
  const textColor = isHeader ? WHITE : isTotal ? DARK : '#333333';
  const rowHeight = 22;

  doc.rect(50, y, 495, rowHeight).fillColor(bg).fill();

  doc.fillColor(textColor).fontSize(isHeader || isTotal ? 9 : 9);
  const colWidths = [220, 80, 80, 115];
  let x = 55;
  cols.forEach((col, i) => {
    const align = i === 0 ? 'left' : 'right';
    doc.text(String(col), x, y + 6, { width: colWidths[i], align });
    x += colWidths[i];
  });

  doc.strokeColor('#e0e0e0').lineWidth(0.3).rect(50, y, 495, rowHeight).stroke();
}

/**
 * Generate a professional P&L PDF report and pipe it to `res`.
 */
function generatePDF(session, res) {
  const doc = new PDFDocument({ margin: 0, size: 'A4' });
  doc.pipe(res);

  const lang = session.language || 'bm';
  const bm = lang === 'bm';

  // ── Cover band ────────────────────────────────────────────────────────────
  doc.rect(0, 0, 595, 120).fillColor(GREEN).fill();

  // Logo area
  doc.fillColor(WHITE).fontSize(28).font('Helvetica-Bold')
     .text('KiraBot', 50, 30);
  doc.fillColor('rgba(255,255,255,0.7)').fontSize(11).font('Helvetica')
     .text(bm ? 'Pembantu Niaga Digital B40' : 'Digital Business Assistant for B40', 50, 62);

  // Report title
  doc.fillColor(WHITE).fontSize(14).font('Helvetica-Bold')
     .text(bm ? 'PENYATA UNTUNG RUGI' : 'PROFIT & LOSS STATEMENT', 50, 86);

  // ── Business info box ──────────────────────────────────────────────────────
  doc.rect(50, 130, 495, 70).fillColor(LIGHT).fill();

  const summaries = session.dailySummaries;
  const periodStart = summaries.length > 0 ? summaries[0].date : session.currentDate;
  const periodEnd   = summaries.length > 0 ? summaries[summaries.length - 1].date : session.currentDate;

  doc.fillColor(DARK).fontSize(13).font('Helvetica-Bold')
     .text(session.businessName || 'My Business', 65, 140);
  doc.fillColor(GREY).fontSize(9).font('Helvetica')
     .text(bm ? `Tempoh Laporan: ${formatDate(periodStart)} — ${formatDate(periodEnd)}`
              : `Reporting Period: ${formatDate(periodStart)} — ${formatDate(periodEnd)}`, 65, 157)
     .text(bm ? `Dijana oleh KiraBot pada ${new Date().toLocaleString('ms-MY')}`
              : `Generated by KiraBot on ${new Date().toLocaleString('en-MY')}`, 65, 170);

  // ── Financial Health Score ────────────────────────────────────────────────
  const score = getFinancialHealthScore(session);
  const loans = getLoanRecommendations(score);

  const scoreX = 380;
  doc.rect(scoreX, 130, 165, 70).fillColor(score >= 60 ? GREEN : score >= 40 ? '#f39c12' : RED).fill();
  doc.fillColor(WHITE).fontSize(9).font('Helvetica')
     .text(bm ? 'SKOR KESIHATAN KEWANGAN' : 'FINANCIAL HEALTH SCORE', scoreX + 10, 140, { width: 145, align: 'center' });
  doc.fillColor(WHITE).fontSize(28).font('Helvetica-Bold')
     .text(`${score}`, scoreX + 10, 152, { width: 145, align: 'center' });
  doc.fillColor('rgba(255,255,255,0.85)').fontSize(9).font('Helvetica')
     .text('/100', scoreX + 10, 183, { width: 145, align: 'center' });

  let y = 215;

  // ── Revenue Section ───────────────────────────────────────────────────────
  doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold')
     .text(bm ? 'PENDAPATAN (JUALAN)' : 'REVENUE (SALES)', 50, y);
  y += 16;

  drawTableRow(doc, y, [
    bm ? 'Item' : 'Item',
    bm ? 'Unit' : 'Units',
    bm ? 'Harga' : 'Price',
    bm ? 'Jumlah' : 'Amount'
  ], true);
  y += 22;

  // Aggregate sales by item
  const salesByItem = {};
  for (const tx of session.transactions) {
    if (tx.type !== 'sales') continue;
    for (const item of tx.items) {
      if (!salesByItem[item.name]) salesByItem[item.name] = { qty: 0, price: item.price, total: 0 };
      salesByItem[item.name].qty += item.qty;
      salesByItem[item.name].total += item.total;
    }
  }

  let totalRevenue = 0;
  for (const [name, data] of Object.entries(salesByItem)) {
    drawTableRow(doc, y, [name, data.qty, formatRM(data.price), formatRM(data.total)]);
    totalRevenue += data.total;
    y += 22;
  }
  if (Object.keys(salesByItem).length === 0) {
    doc.fillColor(GREY).fontSize(9).font('Helvetica')
       .text(bm ? 'Tiada rekod jualan' : 'No sales records', 55, y + 6);
    y += 22;
  }

  drawTableRow(doc, y, [bm ? 'JUMLAH PENDAPATAN' : 'TOTAL REVENUE', '', '', formatRM(totalRevenue)], false, true);
  y += 30;

  // ── Expenses Section ──────────────────────────────────────────────────────
  doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold')
     .text(bm ? 'PERBELANJAAN (KOS)' : 'EXPENSES (COSTS)', 50, y);
  y += 16;

  drawTableRow(doc, y, [bm ? 'Perkara' : 'Item', '', '', bm ? 'Jumlah' : 'Amount'], true);
  y += 22;

  const expenseByItem = {};
  for (const tx of session.transactions) {
    if (tx.type !== 'expense') continue;
    for (const item of tx.items) {
      expenseByItem[item.item] = (expenseByItem[item.item] || 0) + item.amount;
    }
  }

  let totalExpenses = 0;
  for (const [name, amount] of Object.entries(expenseByItem)) {
    drawTableRow(doc, y, [name, '', '', formatRM(amount)]);
    totalExpenses += amount;
    y += 22;
  }
  if (Object.keys(expenseByItem).length === 0) {
    doc.fillColor(GREY).fontSize(9).font('Helvetica')
       .text(bm ? 'Tiada rekod belanja' : 'No expense records', 55, y + 6);
    y += 22;
  }

  drawTableRow(doc, y, [bm ? 'JUMLAH PERBELANJAAN' : 'TOTAL EXPENSES', '', '', formatRM(totalExpenses)], false, true);
  y += 30;

  // ── Net Profit Box ────────────────────────────────────────────────────────
  const netProfit = totalRevenue - totalExpenses;
  const profitColor = netProfit >= 0 ? GREEN : RED;

  doc.rect(50, y, 495, 40).fillColor(profitColor).fill();
  doc.fillColor(WHITE).fontSize(13).font('Helvetica-Bold')
     .text(bm ? 'UNTUNG BERSIH' : 'NET PROFIT', 60, y + 12)
     .text(formatRM(netProfit), 60, y + 12, { width: 480, align: 'right' });
  y += 55;

  // ── Daily Breakdown ───────────────────────────────────────────────────────
  if (session.dailySummaries.length > 0) {
    doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold')
       .text(bm ? 'PRESTASI HARIAN' : 'DAILY PERFORMANCE', 50, y);
    y += 16;

    drawTableRow(doc, y, [
      bm ? 'Tarikh' : 'Date',
      bm ? 'Jualan' : 'Sales',
      bm ? 'Belanja' : 'Expenses',
      bm ? 'Untung Bersih' : 'Net Profit'
    ], true);
    y += 22;

    for (const day of session.dailySummaries) {
      const dayProfit = day.netProfit;
      drawTableRow(doc, y, [
        formatDate(day.date),
        formatRM(day.totalSales),
        formatRM(day.totalExpenses),
        formatRM(dayProfit)
      ]);
      y += 22;
      if (y > 720) { doc.addPage(); y = 50; }
    }
    y += 15;
  }

  // ── Financing Recommendations ─────────────────────────────────────────────
  if (loans.length > 0 && y < 680) {
    doc.rect(50, y, 495, 30 + loans.length * 18).fillColor('#e8f5e9').fill();
    doc.fillColor(GREEN).fontSize(10).font('Helvetica-Bold')
       .text(bm ? '✅ KELAYAKAN PEMBIAYAAN' : '✅ FINANCING ELIGIBILITY', 60, y + 8);
    y += 26;
    doc.fillColor(DARK).fontSize(9).font('Helvetica');
    for (const loan of loans) {
      doc.text(`• ${loan}`, 65, y);
      y += 18;
    }
    y += 10;
  }

  // ── Footer ────────────────────────────────────────────────────────────────
  doc.rect(0, 800, 595, 42).fillColor(GREEN).fill();
  doc.fillColor(WHITE).fontSize(8).font('Helvetica')
     .text('KiraBot — WhatsApp POS Chatbot untuk Usahawan B40 | IIUM Kulliyyah of ICT', 50, 812, { align: 'center', width: 495 })
     .text(bm
       ? 'Laporan ini dijana secara automatik dan boleh digunakan sebagai sokongan permohonan pembiayaan.'
       : 'This report is auto-generated and may be used as supporting documentation for financing applications.',
       50, 824, { align: 'center', width: 495 });

  doc.end();
}

module.exports = { generatePDF };
